

import { Provider } from "react-redux";
import { store } from "../store";
import AuthProvider from "../components/AuthProvider";
import "./globals.css";
import Providers from "@/components/Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
